// <auto-generated />
using AggregatorService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AggregatorService.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AggregatorService.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.ToTable("Character");

                    b.HasAnnotation("Relational:JsonPropertyName", "character");
                });

            modelBuilder.Entity("AggregatorService.Models.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "rank");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "rating");

                    b.Property<int>("SeasonRecordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonRecordId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("AggregatorService.Models.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lost")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "lost");

                    b.Property<int>("Played")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "played");

                    b.Property<int>("Won")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "won");

                    b.HasKey("Id");

                    b.ToTable("Record");

                    b.HasAnnotation("Relational:JsonPropertyName", "season_match_statistics");
                });

            modelBuilder.Entity("AggregatorService.Models.Entry", b =>
                {
                    b.HasOne("AggregatorService.Models.Character", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AggregatorService.Models.Record", "SeasonRecord")
                        .WithMany()
                        .HasForeignKey("SeasonRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("SeasonRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
